Delete unnecessary import
This doesn't do anything useful on python 2 and causes an ImportError on
python 3:

>>> import brotherprint
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "python-brotherprint/brotherprint/__init__.py", line 1, in <module>
    from brotherprint import BrotherPrint
ImportError: cannot import name 'BrotherPrint